import "./HotSelling.css";
import "./Categories.css";
import "./ProductDetails.css";
import "./BuyProduct.css";
import "./Login.css";
import "./Signup.css";
import "./Dashboard.css";
import "./orderPlaced.css";
import "./Cart.css";
import "./Checkout.css";
import "./AdminLayout.css"